package ui.decklist

val SAMPLE_DECK_LIST_SAMPLE_ONE = DeckListsItem(DeckName("DECK ONE"), DeckId(""))
val SAMPLE_DECK_LIST_SAMPLE_TWO = DeckListsItem(DeckName("DECK TWO"), DeckId(""))
val SAMPLE_DECK_LIST_SAMPLE_THREE = DeckListsItem(DeckName("DECK THREE"), DeckId(""))
val SAMPLE_DECK_LIST_SAMPLE_FOUR = DeckListsItem(DeckName("DECK FOUR"), DeckId(""))
val SAMPLE_DECK_LIST_SAMPLE_FIVE = DeckListsItem(DeckName("DECK FIVE"), DeckId(""))
val SAMPLE_DECK_LIST_SAMPLE_SIX = DeckListsItem(DeckName("DECK SIX"), DeckId(""))
val SAMPLE_DECK_LIST_SAMPLE_SEVEN = DeckListsItem(DeckName("DECK SEVEN"), DeckId(""))

val SAMPLE_DECK_LIST = listOf(
    SAMPLE_DECK_LIST_SAMPLE_ONE,
    SAMPLE_DECK_LIST_SAMPLE_TWO,
    SAMPLE_DECK_LIST_SAMPLE_THREE,
    SAMPLE_DECK_LIST_SAMPLE_FOUR,
    SAMPLE_DECK_LIST_SAMPLE_FIVE,
    SAMPLE_DECK_LIST_SAMPLE_SIX,
    SAMPLE_DECK_LIST_SAMPLE_SEVEN
)